title: Sooty Docs
description: Docs for the Sooty dialogue system

remote_theme: just-the-docs/just-the-docs

# collections:
#   features:
#     #permalink: "/:collection/:path/"
#     output: true
#   visual_novel:
#     #permalink: "/:collection/:path/"
#     output: true

# just_the_docs:
#   # Define which collections are used in just-the-docs
#   collections:
#     features:
#       name: Features
#     visual_novel:
#       name: Visual Novel
